addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.eed3si9n"          % "sbt-assembly" % "2.1.5")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "7.4.0")
addSbtPlugin("ch.epfl.scala"         % "sbt-bloop"    % "2.0.18")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"   % "5.6.0")
